version: '3.8'
services:
  postgresdb:
    image: postgres:15-alpine
    container_name: bike-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bike_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bike-rental_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - db_data:/var/bike/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: ./bike-app
    container_name: bike-app-node
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgresdb
      DB_USER: bike_user
      DB_PASSWORD: 123
      DB_NAME: bike-rental_db
      DB_PORT: 5432
      NODE_DOCKER_PORT: 8080

volumes:
  db_data: